FROM golang:1.20-alpine as builder

WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o /build/ports-service ./cmd/ports

FROM alpine:3.17

WORKDIR /app
COPY --from=builder /build/ports-service .

CMD ["./ports-service"]

